# THE SPARKS FOUNDATION
## GRIP June 2021
### Author : Sreelekshmi R V
### Task 1 : Object Detection

In [8]:
#importing necessary modules
import cv2
import numpy as np

In [9]:
#declaring thresholds
whT = 320
confThreshold = 0.6

In [10]:
#loading coconames
classesFile = 'coco.names'
className = []
with open(classesFile, 'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

In [11]:
#loading YOLO weights and configuration files
model_config = 'yolov3.cfg'
model_weights = 'yolov3.weights'

In [12]:
#setting opencv as backend and cpu as target
net = cv2.dnn.readNet(model_config, model_weights)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)

In [13]:
#function for object detection
def findObjects(output, img):
    hT, wT, cT = img.shape
    bbox = []
    classIds = []
    confs = []

    for output in outputs:
        for det in output:
            scores = det[5:]
            classId = np.argmax(scores)
            confidence = scores[classId]
            if confidence > confThreshold:
                w, h = int(det[2]*wT), int(det[3]*hT)
                x, y = int((det[0]*wT)-w/2), int((det[1]*hT)-h/2)
                bbox.append([x, y, w, h])
                classIds.append(classId)
                confs.append(float(confidence))

    indices = cv2.dnn.NMSBoxes(bbox, confs, confThreshold, nms_threshold=0.3)
    print(indices)
    for i in indices:
        i = i[0]
        box = bbox[i]
        x, y, w, h = box[0], box[1], box[2], box[3]
        cv2.rectangle(img, (x, y), (x+w, y+h), (255,0,255), 2)
        cv2.putText(img, f'{classNames[classIds[i]].upper()} {int(confs[i]*100)}%',
                    (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (47,255,173), 2,cv2.LINE_AA)

In [14]:
#loading video file
cap = cv2.VideoCapture('inceptionscene.avi')
while True :
    success, img = cap.read()
    blob = cv2.dnn.blobFromImage(img, 1/255, (whT, whT), [0, 0, 0], 1, crop= False)
    net.setInput(blob)

    layerNames = net.getLayerNames()
    outputNames = [layerNames[i[0]-1] for i in net.getUnconnectedOutLayers()]
    print(outputNames)
    
    outputs = net.forward(outputNames)
    findObjects(outputs, img)

    cv2.imshow('image', img)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

['yolo_82', 'yolo_94', 'yolo_106']
[[ 7]
 [ 6]
 [13]
 [ 4]
 [ 3]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 7]
 [ 6]
 [13]
 [ 4]
 [ 3]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[1]
 [3]
 [9]
 [6]
 [7]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 1]
 [ 4]
 [10]
 [ 0]
 [13]
 [ 7]
 [ 8]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 6]
 [13]
 [ 1]
 [ 3]
 [ 0]
 [16]
 [11]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 5]
 [ 3]
 [10]
 [ 2]
 [ 1]
 [ 8]
 [13]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 5]
 [ 2]
 [ 1]
 [ 9]
 [ 7]
 [12]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 3]
 [ 5]
 [ 2]
 [12]
 [ 0]
 [ 9]
 [11]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 4]
 [ 1]
 [ 2]
 [ 8]
 [ 0]
 [12]
 [10]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 1]
 [ 0]
 [ 2]
 [ 9]
 [ 4]
 [13]
 [ 7]
 [11]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 1]
 [11]
 [ 0]
 [ 3]
 [14]
 [16]
 [ 6]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 2]
 [10]
 [ 1]
 [ 4]
 [ 7]
 [14]]
['yolo_82', 'yolo_94', 'yolo_106']
[[ 1]
 [13]
 [ 0]
 [10]
 [ 3]
 [16]
 [ 6]
 [ 5]]
['yolo_82